name: Generate Snake Game

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "12 43 * * *"
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main # Regenerates on push to main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ Ashraf-Morningstar }} # Uses your username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and Push Artifacts
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "chore: update contribution snake" || echo "No changes to commit."
          git push
